### PR TITLE
Update unit tests and bump snapshot date

### PR DESCRIPTION
**Pull request by knauth**
Update the unit tests to account for the libtracefs breaking change (outlined in b6119c0, see more [here](https://git.kernel.org/pub/scm/libs/libtrace/libtracefs.git/commit/?id=dde4869918e613b257af5a98f3e7c5d1c93055bc))

With that issue accounted with, it is safe to bump the date-snapshot dependencies to today.

### CODE REVIEW

**Review by tzstoyanov — CHANGES_REQUESTED** [review]
Since we have a CI run with `latest`, I think it makes more sense to use the required versions of these libraries here, instead of snapshots from given date. The required versions are listed in `setup.py`, bump the libtracefs version to 1.4.1 there and pin to those versions in `repos`.  May be that will require some changes in the `date-snapshot.sh` script, to get version with given tag instead of given date.

**Comment by knauth** [comment]
I have a couple of concerns about this approach, mainly related to version tag syntax. Here are some version tags from our four dependencies:
```
libtraceevent-1.6.0
libtraceevent-1.6.1
```
```
libtracefs-1.4.0
libtracefs-1.4.1
```
```
trace-cmd-v3.1
trace-cmd-v3.1.1
```
```
kernelshark-v2.0
kernelshark-v2.0.1
```

As you can see, these are nonstandard, with varying lengths and prefixes. This makes translating from a standard input (i.e. `v2.0.1`) to the actual tag string challenging. We could develop a parser, or, more simply, just ask users to provide the actual tag string in their input files. Both of these come with drawbacks, though. A parser complex enough to account for all the cases here would risk unexpected behavior if provided with something we didn't account for in development. A tag string in the input would preclude automated version tag changes, since if we're going to build a bot to understand and change the version tag strings, we might as well build a parser to understand them.

Finally, this would lock us to major version releases of the dependencies. That might not be a bad thing, but we might want to grab a latest feature or bugfix before said major release.

To me, while this is a nice syntactic feature, it doesn't provide major functionality improvements over simply providing the script the date of the version update, and might cause confusion or unexpected behavior in the future.

**Comment by tzstoyanov** [comment]
I think a tag string should be used. There is no need to implement a parser, at least at this point. The main motivation for using tags vs dates is that the CI must verify the changes with the official dependencies, used in the trace-cruncher build. This will not lock us to major version only, as any of these libraries have minor bug fix releases. And we can still run the CI with the latest features, even before they get released - using the `--latest` option that you implemented. The only limitation of this approach is that we cannot easily automate CI runs with different versions of these dependencies - but in any case I think that this is dangerous, even using dates, as most probably random combinations of snapshots may not be compatible with each other, even if they are from the same date.

**Comment by knauth** [comment]
OK, this all makes sense to me- will push the change soon.

**Comment by warthog9** [comment]
I'll broaden this slightly here: I'd just leave it as a straight pass-through for a git reference, tag, sha, branch name, etc - if we just treat the field as "git should groks this" (mostly noting this here since already mentioned to @knauth )

**Pull request merged**
